### ISSUE TITLE
Add in validation of `CITATION.cff` file (if it exists)

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/model-config-tests#42]
See https://github.com/ACCESS-NRI/access-esm1.5-configs/pull/41#issuecomment-2270818063

Not all `*-configs`-style repositories have this yet, but it seems like a good thing to add to the overall `model-config-tests` infrastructure. 

Make it a set of steps like:
```yaml
 - uses: actions/checkout@v4

 - name: Check for CITATION.cff
   id: citation-file
   run: |
     if [ -f "CITATION.cff" ]; then
       echo "exists=true" >> $GITHUB_OUTPUT
     fi
 - name: Validate CITATION.cff
   if: steps.citation-file.outputs.exist
   uses: citation-file-format/cffconvert-github-action@2.0.0
   with:
     args: "--validate"
```
